# syntax=docker/dockerfile:1.7
FROM node:22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . . 

FROM gcr.io/distroless/nodejs22-debian13
WORKDIR /app
COPY --from=build /app/package*.json /app/
COPY --from=build /app/src  /app/src
COPY --from=build /app/node_modules /app/node_modules
USER nonroot
EXPOSE 3002
CMD ["src/server.js"]




