#---------Build Stage--------------------

FROM node:22 AS build 
WORKDIR /app
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev
COPY . .

#--------------Runtime stage--------------
FROM gcr.io/distroless/nodejs22-debian13
WORKDIR /app
COPY --from=build /app/src ./src
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

USER nonroot
EXPOSE 3001
CMD ["/src/server.js"]
